### PR TITLE
Verify email

### LINKED ISSUE #6952: Updating email address gave a 'Failed to verify email' screen but had updated email address
**What**

This is the screen I got after updating my email address – but I did then get the “Welcome to the Wellcome Collection” email

Screenshot 2021-08-24 at 11 33 28

**Where**

https://wellcome.slack.com/archives/CUA669WHH/p1629801230164600

### PR DESCRIPTION
**Pull request by gestchild**
Fixes #6952

Not sure how bullet proof using the message in the url to determine what to display is, but can't see another way

### CODE REVIEW

File: identity/webapp/pages/account/validated.tsx [hunk 1]
```diff
@@ -16,13 +16,14 @@ type Props = {
 };
 
 const ValidatedPage: NextPage<Props> = ({ success, message }) => {
+  const urlUsed = message === 'This URL can be used only once';
```
Comment (jamieparkinson) [inline identity/webapp/pages/account/validated.tsx:19]: Maybe put a comment linking to https://auth0.com/docs/brand-and-customize/email/email-template-descriptions#redirect-to-results-for-verification-email-template as this is indeed weird but necessary

**Review by jamieparkinson — APPROVED** [review]

**Review by davidpmccormick — APPROVED** [review]
