### PR TITLE
Fix link in credit info

### LINKED ISSUE #6317: Broken link in credit info
**What**
Links contained in the 'Credit' info on a digitised item are broken.
These links should go to the work page itself. 

The user should be able to copy+paste the contents of that field and have correct linking.

**Where**
https://wellcomecollection.org/works/bs9j8bnt/items

Screenshot 2021-03-31 at 16 46 13

### PR DESCRIPTION
**Pull request by davidpmccormick**
Fixes #6317

### CODE REVIEW

File: common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx [hunk 1]
```diff
@@ -238,7 +238,7 @@ const ViewerSidebarPrototype: FunctionComponent<Props> = ({
             </p>
             {credit && (
               <p>
-                <a href="https:wellcomecollection.org/works/{work.id}">
+                <a href={`https://wellcomecollection.org/works/${work.id}`}>
```
Comment (jamesgorrie) [inline common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx:241]: Why aren't we using a next link? And also making this a absolute, not relative link?

File: common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx [hunk 2]
```diff
@@ -252,9 +255,9 @@ const ViewerSidebarPrototype: FunctionComponent<Props> = ({
             </p>
             {credit && (
               <p>
-                <a href="https:wellcomecollection.org/works/{work.id}">
-                  {credit}
-                </a>
+                <NextLink href={`/works/${work.id}`}>
```
Comment (jamesgorrie) [inline common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx:258]: Could we use the `WorkLink`? We should probably add a source then too.

Sorry to be such a massive pedant on this.

Comment (davidpmccormick) [reply common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx:258]: Yeah, I didn't use it because I couldn't see a relevant `source`. What are the sources for, and what should this one be, then?

Comment (jamesgorrie) [reply common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx:258]: It's used in tracking. Basically we would able to see how many pageviews to work pages were generated by this component.

**Review by gestchild — APPROVED** [review]
