### PR TITLE
fix spacing under anchor links

### LINKED ISSUE #6098: Spacing between anchor list and text
**What**

We need to apply some spacing between the anchor list and a `h2` as you can see here

Screenshot 2021-02-11 at 16 11 12

**Where**
Found on Chrome
https://preview.wellcomecollection.org/pages/YBGcehMAAB4AjW_c

### PR DESCRIPTION
**Pull request by gestchild**
Fixes #6098

Before:
Screenshot 2021-02-16 at 17 20 43

After:
Screenshot 2021-02-16 at 17 19 43

### CODE REVIEW

File: common/views/components/Body/Body.tsx [hunk 1]
```diff
@@ -274,225 +274,235 @@ const Body: FunctionComponent<Props> = ({
           isLanding={isLanding}
         />
       )}
-      {/* // TO '|||||check when no body content */}
+
```
Comment (jamesgorrie) [inline common/views/components/Body/Body.tsx:277]: 😄

**Review by jamesgorrie — APPROVED** [review]
