### PR TITLE
500 issue, fix issue with params items not a string and returning back an array on works.

### LINKED ISSUE #5807: Non Javascript version new search returns error 500 if user picks physical and digital location within the search filter due to duplicated query params
Current state :

on the non js version ()

https://www-stage.wellcomecollection.org/works?query=www&production.dates.from=&production.dates.to=&items.locations.type=DigitalLocation&items.locations.type=PhysicalLocation&sort=&sortOrder=desc

working version 

https://www-stage.wellcomecollection.org/works?query=www&items.locations.type=DigitalLocation%2CPhysicalLocation&sort=production.dates&sortOrder=desc

Need to make sure not to duplicate query params and correct form query strings

### PR DESCRIPTION
**Pull request by ishouty**
search returns error 500 if user enters via url qs( work type, locationType ) within the search filter due to serialising in routes .

The non js version or if a user adds on search manually query param (workType, locationType)  more than once, it is an array rather than a string. 

Written functionality to check any params required in works and convert them to string before processing toQuery. 

closes #5807

These items include
* Worktype
* locationType

### CODE REVIEW

File: common/services/catalogue/routes.js [hunk 1]
```diff
@@ -3,6 +3,26 @@ import { type NextLinkType } from '@weco/common/model/next-link-type';
 
 type Params = { [key: string]: any };
 export type UrlParams = { [key: string]: string };
+
+export function serialiseQueryParams(
```
Comment (jamesgorrie) [inline common/services/catalogue/routes.js:7]: I'd move this into a util method as it isn't related to our routes.

Comment (ishouty) [reply common/services/catalogue/routes.js:7]: sounds good

File: common/utils/serialise-url.ts [hunk 2]
```diff
@@ -0,0 +1,27 @@
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+export type QueryParams = { [key: string]: any };
```
Comment (jamesgorrie) [inline common/utils/serialise-url.ts:2]: Should this rather be `querystring.ParsedUrlQuery`?

File: common/utils/serialise-url.ts [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  // query contains global context, being specific on parsing
+  const itemToConvert = Object.keys(newParams).filter(param => {
+    if (paramsToConvert.includes(param)) {
+      return true;
+    }
+    return false;
+  });
+
+  // convert the items to string else return back
+  itemToConvert.forEach(key => {
```
Comment (jamesgorrie) [inline common/utils/serialise-url.ts:19]: The reason this is mutating the original is because we're mutating an existing object.

A more safe way to do this would be:
```ts
const parsedQuery = Object.entries(query).reduce((acc, [key, val]) => {
  return {
    ...acc,
    [key]: parseQueryParam(val)
  }
}, {});
```

Why do we want to send a list of params to parse? If we don't, we can 100% guarantee that you will get a `{ [key: string]: string }` type back.

File: common/utils/serialise-url.ts [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+    newParams[key] = parseQueryParam(newParams[key]);
+  });
+  return newParams;
+}
+
+export function parseQueryParam(param: string | []): string {
```
Comment (jamesgorrie) [inline common/utils/serialise-url.ts:25]: Assuming we mean:
```suggestion
export function parseQueryParam(param: string | string[]): string {
```

File: common/utils/serialise-url.ts [hunk 5]
```diff
@@ -0,0 +1,27 @@
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+export type ParsedUrlQuery = { [key: string]: any };
```
Comment (jamesgorrie) [inline common/utils/serialise-url.ts:2]: Apologies, I meant the native type from `@types/node` `querystring` that is on the `context`. 
[e.g.](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgBQIZQM4FMAmBVKAGwEUBXLKATzgF84AzKCEOAcgEdyqMYpgA7AOasA3AFgAUJIDGEfjzgCAbqkLAcALhTps+ImQrUAvIjgBrLJS1Jlq9Vt7latcRNnz4KtZu2ZcBEi5jUwsrNi91VgAac0sAJi0AbVYInGjwuzSAXRcgA)

Comment (ishouty) [reply common/utils/serialise-url.ts:2]: ahh perfect .. thank you

File: common/utils/serialise-url.ts (hunk 3 above)
Comment (ishouty) [reply common/utils/serialise-url.ts:19]: Nice, yeah the solution is cleaner and safer, yeah my issue is query also contains these properties 

toggles
globalAlert
popupDialog
openingTimes
memoizedPrismic
query
workType

which are not really what i want to parse or modify. 

Should we just still allow this?

File: common/utils/serialise-url.ts [hunk 6]
```diff
@@ -0,0 +1,17 @@
...
+      ...acc,
+      [key]: parseQueryParam(val),
+    };
+  }, {});
+  return parsedQuerys;
+}
+
+export function parseQueryParam(param: string | string[]): string {
+  const parseParam = Array.isArray(param) ? param.join(',') : param;
+  return typeof parseParam === 'string' ? parseParam : '';
```
Comment (jamesgorrie) [inline common/utils/serialise-url.ts:16]: Do we want to pass an empty string, or an `undefined`?

**Review by jamesgorrie — APPROVED** [review]
Looks good, thanks for working through that with me.

File: common/utils/serialise-url.ts (hunk 6 above)
Comment (ishouty) [reply common/utils/serialise-url.ts:16]: i thought i would get type issues but undefined seems to be fine even though return type is undefined.
