### PR TITLE
Fix breadcrumb

### LINKED ISSUE #5675: Archive breadcrumbs behaving inconsistently
**What**
When navigating the archive tree, the breadcrumbs appear not to be updating consistently.

1. Run this search
https://wellcomecollection.org/works?query=sa%2Ffpa%20birmingham
Screenshot 2020-10-28 at 17 11 51

2. Select the 2nd result in list https://wellcomecollection.org/works/fne6savj 

Screenshot 2020-10-28 at 17 12 44

3. Navigate from there to https://wellcomecollection.org/works/dy7gmg76 (section below above)

Screenshot 2020-10-28 at 17 13 54

4. Breadcrumbs now show Birmingham (the section title), rather than Family Planning Association (the collection title)

**What you'd expect**
I would expect that navigating at any level of the archive, that the Collection title remain the first option in the breadcrumb:
`Collection name` > `[Levels within`] > `Current location`

### PR DESCRIPTION
**Pull request by gestchild**
Fixes #5675

We were deciding which partOf item to use as the parent work based on referenceNumber, but it looks like they don't always follow the same pattern.

At the moment there is only ever one item in the partOf array, so we can just get the first one.

If in the future partOf contains more than one item, we’ll need a way to discern which one is correct

### CODE REVIEW

File: common/utils/works.js [hunk 1]
```diff
@@ -274,10 +274,7 @@ function makeArchiveAncestorArray(partOfArray, nextPart) {
   if (!nextPart) return partOfArray;
   return makeArchiveAncestorArray(
     [...partOfArray, parsePart(nextPart)],
-    nextPart.partOf &&
-      nextPart.partOf.find(part => {
-        return nextPart.referenceNumber.includes(part.referenceNumber);
-      })
+    nextPart.partOf && nextPart.partOf[0]
```
Comment (davidpmccormick) [inline common/utils/works.js:277]: I think we can do this `nextPart.partOf?.[0]`

**Review by davidpmccormick — APPROVED** [review]
